# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  mcp-cmd = nodeEnv.buildNodePackage {
    name = "mcp-cmd";
    packageName = "mcp-cmd";
    version = "0.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/mcp-cmd/-/mcp-cmd-0.1.0.tgz";
      sha512 = "eUBA+9JuePXPQ34GRixNTafraiJvqaiTigFOUxmRxo2TH2xJY4AQfhjnNepL1IhUeM8l1rI75E7RrlTWJ7eaDA==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A Node.js CLI for managing persistent MCP servers in the background";
      homepage = "https://github.com/developit/mcp-cmd";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
