# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {};
in
{
  ccstatusline = nodeEnv.buildNodePackage {
    name = "ccstatusline";
    packageName = "ccstatusline";
    version = "2.0.23";
    src = fetchurl {
      url = "https://registry.npmjs.org/ccstatusline/-/ccstatusline-2.0.23.tgz";
      sha512 = "6qh7U7+RoxdB/6KHWDRBhkHuJuXy7pBpgHPzZscDOu0/0UISunEDidkZIaAx1O/l7fnMk4FxqXjviTheVgeUYQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A customizable status line formatter for Claude Code CLI";
      homepage = "https://github.com/sirmalloc/ccstatusline#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
